#!/usr/bin/perl
# Copyright © 2013 EDF SA
# Contact:
#       CCN - HPC <dsp-cspit-ccn-hpc@edf.fr>
#       1, Avenue du General de Gaulle
#       92140 Clamart
#
# Authors: Mehdi Dogguy <mehdi.dogguy@edf.fr>
#          Antonio Russo <antonio-externe.russo@edf.fr>
#
# This program is free software; you can redistribute in and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details. On Calibre
# systems, the full text of the GNU General Public License can be
# found in `/usr/share/common-licenses/GPL'.

use strict;
use Getopt::Long;
use Sys::Hostname;
use Neos;

use Switch;

# Job parameters
my $job_partition = Neos::get_partition ();
my $resolution = Neos::get_vncres ();
my $scenario = "";
my $result = GetOptions ("resolution=s" => \$resolution,
                         "scenario=s"   => \$scenario,
                         "config=s"     => \&Neos::config_file_handler,
);

# Save user specified configuration (cli options and .conf file content)
Neos::set_param('resolution', $resolution);
Neos::set_param('scenario', Neos::get_scenario_name ($scenario));
if ($ENV{'ENVIRONMENT'} eq "BATCH") {
    Neos::set_param('password', Neos::gen_password ());
}
Neos::dump_config();

if (Neos::is_good_partition($job_partition)) {
    Neos::init ();

    Neos::load_scenario($scenario);
    Neos::run_action('main');
} else {
    die("$job_partition is not configured for Neos.");
}
